// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users_rbac.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listUsers = `-- name: ListUsers :many
SELECT id, username, hashed_password, full_name, password_changed_at, created_at, role, tenant_id
FROM users
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.FullName,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.Role,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByIDFull = `-- name: GetUserByIDFull :one
SELECT id, username, hashed_password, full_name, password_changed_at, created_at, role, tenant_id
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByIDFull(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDFull, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Role,
		&i.TenantID,
	)
	return i, err
}

const getUserByUsernameFull = `-- name: GetUserByUsernameFull :one
SELECT id, username, hashed_password, full_name, password_changed_at, created_at, role, tenant_id
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsernameFull(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameFull, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Role,
		&i.TenantID,
	)
	return i, err
}

const createUserWithRole = `-- name: CreateUserWithRole :one
INSERT INTO users (
  username,
  hashed_password,
  full_name,
  role,
  tenant_id
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, username, hashed_password, full_name, password_changed_at, created_at, role, tenant_id
`

type CreateUserWithRoleParams struct {
	Username       string     `json:"username"`
	HashedPassword string     `json:"hashed_password"`
	FullName       string     `json:"full_name"`
	Role           UserRole   `json:"role"`
	TenantID       *uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CreateUserWithRole(ctx context.Context, arg CreateUserWithRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithRole, arg.Username, arg.HashedPassword, arg.FullName, arg.Role, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Role,
		&i.TenantID,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, tenant_id = $3
WHERE id = $1
RETURNING id, username, hashed_password, full_name, password_changed_at, created_at, role, tenant_id
`

type UpdateUserRoleParams struct {
	ID       int32      `json:"id"`
	Role     UserRole   `json:"role"`
	TenantID *uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Role,
		&i.TenantID,
	)
	return i, err
}

const updateUserTenant = `-- name: UpdateUserTenant :one
UPDATE users
SET tenant_id = $2
WHERE id = $1
RETURNING id, username, hashed_password, full_name, password_changed_at, created_at, role, tenant_id
`

type UpdateUserTenantParams struct {
	ID       int32      `json:"id"`
	TenantID *uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateUserTenant(ctx context.Context, arg UpdateUserTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTenant, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Role,
		&i.TenantID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const addUserProvider = `-- name: AddUserProvider :exec
INSERT INTO user_providers (user_id, provider_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserProviderParams struct {
	UserID     int32     `json:"user_id"`
	ProviderID uuid.UUID `json:"provider_id"`
}

func (q *Queries) AddUserProvider(ctx context.Context, arg AddUserProviderParams) error {
	_, err := q.db.Exec(ctx, addUserProvider, arg.UserID, arg.ProviderID)
	return err
}

const removeUserProvider = `-- name: RemoveUserProvider :exec
DELETE FROM user_providers
WHERE user_id = $1 AND provider_id = $2
`

type RemoveUserProviderParams struct {
	UserID     int32     `json:"user_id"`
	ProviderID uuid.UUID `json:"provider_id"`
}

func (q *Queries) RemoveUserProvider(ctx context.Context, arg RemoveUserProviderParams) error {
	_, err := q.db.Exec(ctx, removeUserProvider, arg.UserID, arg.ProviderID)
	return err
}

const listUserProviders = `-- name: ListUserProviders :many
SELECT provider_id FROM user_providers
WHERE user_id = $1
`

func (q *Queries) ListUserProviders(ctx context.Context, userID int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserProviders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var provider_id uuid.UUID
		if err := rows.Scan(&provider_id); err != nil {
			return nil, err
		}
		items = append(items, provider_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

